---
- name: Убрать cdrom из apt sources (для корректного update)
  replace:
    path: /etc/apt/sources.list
    regexp: '^deb cdrom:'
    replace: '# deb cdrom:'
  when: ansible_os_family == "Debian"

- name: Обновить списки пакетов (apt update)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Установить Nginx
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Включить и запустить Nginx
  service:
    name: nginx
    enabled: yes
    state: started

