---
- name: Развертывание стека WordPress (Nginx + PHP-FPM + MariaDB)
  hosts: targets
  become: true

  roles:
    - nginx
    - mariadb

  tasks:
    # 0. Устанавливаем пакеты: PHP-FPM и зависимости
    - name: Установить PHP-FPM
      apt:
        name:
          - php-fpm                # установит версию по умолчанию из репозитория
          - php-mysql
          - unzip
        state: present
      when: ansible_os_family == "Debian"

    # 1. Узнаём, какая версия PHP реально установилась (например, 8.1, 8.2)
    - name: Определить версию PHP-FPM
      shell: dpkg -l | grep php-fpm | awk '{print $2}' | sed 's/php-fpm//' | head -n1
      register: php_fpm_version_raw
      changed_when: false
      when: ansible_os_family == "Debian"
      check_mode: no

    - name: Записать версию PHP в переменную
      set_fact:
        php_fpm_service_name: "php{{ php_fpm_version_raw.stdout }}-fpm"
      when: php_fpm_version_raw.stdout != ""

    # Если по какой-то причине версия не определилась, ставим запасной вариант (частый кейс)
    - name: Задать запасное имя службы PHP-FPM (fallback)
      set_fact:
        php_fpm_service_name: "php8.1-fpm"
      when: php_fpm_version_raw.stdout == ""

    # Запускаем PHP 

    - name: Включить и запустить PHP-FPM (версия определена динамически)
      service:
        name: "{{ php_fpm_service_name }}"
        enabled: yes
        state: started

